// src/components/badge.tsx
import { JSX, splitProps } from "solid-js";
import { cva, type VariantProps } from "class-variance-authority";

import { cn } from "@/lib/utils";

const badgeVariants = cva(
  "inline-flex items-center rounded-md border px-2.5 py-0.5 text-xs font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2",
  {
    variants: {
      variant: {
        default: "border-transparent bg-primary text-primary-foreground shadow hover:bg-primary/80",
        secondary: "border-transparent bg-secondary text-muted-foreground hover:bg-secondary/80",
        destructive:
          "border-transparent bg-destructive text-destructive-foreground shadow hover:bg-destructive/80",
        outline: "text-foreground",
      },
    },
    defaultVariants: {
      variant: "default",
    },
  },
);

export interface BadgeProps
  extends JSX.HTMLAttributes<HTMLDivElement>,
    VariantProps<typeof badgeVariants> {}

function Badge(props: BadgeProps) {
  const [local, others] = splitProps(props, ["variant", "class"]);

  const className = badgeVariants({ variant: local.variant, className: local.class });

  return <div class={cn(className)} {...others} />;
}

export { Badge, badgeVariants };

// src/lib/components/badge.svelte
<script lang="ts">
	import { cva, type VariantProps } from 'class-variance-authority';
	import type { HTMLAttributes } from 'svelte/elements';

	const badgeVariants = cva(
		'inline-flex items-center rounded-md border px-2.5 py-0.5 text-xs font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2',
		{
			variants: {
				variant: {
					default:
						'border-transparent bg-primary text-primary-foreground shadow hover:bg-primary/80',
					secondary: 'border-transparent bg-secondary text-muted-foreground hover:bg-secondary/80',
					destructive:
						'border-transparent bg-destructive text-destructive-foreground shadow hover:bg-destructive/80',
					outline: 'text-foreground'
				}
			}
		}
	);

	interface $$Props extends HTMLAttributes<HTMLDivElement>, VariantProps<typeof badgeVariants> {}

	export let variant: $$Props['variant'] = 'default';
</script>

<div class={badgeVariants({ variant, class: $$props.class })}>
	<slot />
</div>
